apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-pipeline
  description: CI/CD for Flask app
serialPipeline:
  stages:
    - targetId: dev
      profiles: ["dev"]
    - targetId: staging
      profiles: ["staging"]
    - targetId: prod
      profiles: ["prod"]
